table D_Calendario
	lineageTag: 72aa8770-cd35-40a1-88e7-685df2cc8acf

	column Data
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7b54c748-f192-4204-b85e-c8e7dcb97d54
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: fa79266a-7ebd-4a12-8fc4-62e08418cbc3
			defaultHierarchy: LocalDateTable_839ec521-8689-4c5d-8e76-b05e62896f68.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: c6eee959-92a5-4f84-beb8-d0f5d437663d
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: fb92d3ce-cc22-4e87-b895-26686ff42654
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: 9fa2bce3-dc9f-491a-8f91-75fbfcb8183f
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: 2dede9d8-4f5b-4dcd-88f4-b4d2c3cbf6d3
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: 90397361-db1e-4ca9-a640-8147b8f3f884
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	partition D_Calendario = m
		mode: import
		source =
				let
				    Dt_Inicio = #date(2020, 1, 1),
				    Dt_Atual = DateTime.Date(DateTime.LocalNow()),
				    Duracao = Duration.From(Number.From(Dt_Atual - Dt_Inicio)),
				    ListaDatas = List.Dates(Dt_Inicio, Number.RoundDown(Duration.Days(Duracao)), #duration(1, 0, 0, 0)),
				    D_Calendario = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {"Data"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(D_Calendario,{{"Data", type date}}),
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Data]), Int64.Type),
				    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
				    #"Dia Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Dia", each Date.Day([Data]), Int64.Type),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Dia Inserido", "Nome do Dia", each Date.DayOfWeekName([Data]), type text)
				in
				    #"Nome do Dia Inserido"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

