table UnidadesEF
	lineageTag: b950f281-66dc-4dbd-b64d-4e3ac0dc16ef

	measure 'faturamento dividido por Meta' =
			
			DIVIDE(SUM('UnidadesEF'[faturamento]), SUM('UnidadesEF'[Meta]))
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 43fc6ff3-67ee-4a85-97f7-48eefa15dfd8

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'faturamento dividido por supermeta' =
			
			DIVIDE(SUM('UnidadesEF'[faturamento]), SUM('UnidadesEF'[supermeta]))
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 2e8e1538-3acc-4128-8d82-e463d302b9f0

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'compraram dividido por atendidos' =
			
			DIVIDE(SUM('UnidadesEF'[compraram]), SUM('UnidadesEF'[atendidos]))
		formatString: 0%;-0%;0%
		lineageTag: d07b80b5-d589-4cfe-9856-94f6bf82c6dc

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'agendamentos dividido por leads+20' =
			
			DIVIDE(SUM('UnidadesEF'[agendamentos]), SUM('UnidadesEF'[leads+20]))
		formatString: 0%;-0%;0%
		lineageTag: c440791c-2195-4935-bcc7-ca2dda7550d1

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'invest mídias dividido por leads+20' =
			
			DIVIDE(
				SUM('UnidadesEF'[invest mídias]),
				SUM('UnidadesEF'[leads+20])
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: c5d127c5-4bb8-4e9d-8d37-3812a05192e3

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'agendamentos menos atendidos' =
			
			SUM('UnidadesEF'[agendamentos]) - SUM('UnidadesEF'[atendidos])
		lineageTag: f0abd12f-00e7-4985-bf4c-e0dc24b67d27

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalSubtraction"
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'agendamentos menos atendidos dividido por agendamentos' =
			
			DIVIDE([agendamentos menos atendidos], SUM('UnidadesEF'[agendamentos]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 93190407-6a98-44aa-a10d-a7edf0f4ccdc

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	column 1
		dataType: int64
		formatString: 0
		lineageTag: 3083f9fd-85fd-4408-a159-22e0d71520ec
		summarizeBy: sum
		sourceColumn: 1

		annotation SummarizationSetBy = Automatic

	column Franquia
		dataType: string
		lineageTag: 835e93fd-b299-4ef2-bd26-9561bc8a4f78
		summarizeBy: none
		sourceColumn: Franquia

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: string
		lineageTag: bf061af3-4189-4b40-946a-20c3644382a6
		summarizeBy: none
		sourceColumn: Mês
		sortByColumn: data

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Meta
		dataType: decimal
		lineageTag: 80234eb4-d25f-43aa-88c2-b8ef8ef45802
		summarizeBy: sum
		sourceColumn: Meta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column supermeta
		dataType: decimal
		lineageTag: 89a635e1-55fa-470f-959e-1639912363a2
		summarizeBy: sum
		sourceColumn: supermeta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column faturamento
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 27ade852-a7a9-4571-8825-fac7e4d8afcb
		summarizeBy: sum
		sourceColumn: faturamento

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column atendidos
		dataType: double
		lineageTag: 1dadeff1-c9d5-4c08-ba4c-82c21b921889
		summarizeBy: sum
		sourceColumn: atendidos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column compraram
		dataType: double
		lineageTag: e46e6feb-282f-4d95-832a-8ee4d3c7edef
		summarizeBy: sum
		sourceColumn: compraram

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ticket Médio'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: b8b8729b-5e07-444b-aba7-f804e9a0d285
		summarizeBy: sum
		sourceColumn: Ticket Médio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'invest mídias'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: a7d01c5c-ce04-4087-a46d-cca84ff32154
		summarizeBy: sum
		sourceColumn: invest mídias

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column alcance
		dataType: double
		lineageTag: 6fcf21df-eeba-4348-a78e-cdd36bbb7f32
		summarizeBy: sum
		sourceColumn: alcance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column leads
		dataType: double
		lineageTag: 6e3904c3-7aec-4d18-af3b-f0a16f4fdd50
		summarizeBy: sum
		sourceColumn: leads

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column leads+20
		dataType: double
		lineageTag: 8bfbae7d-2334-4d14-bb61-17af1d6e4266
		summarizeBy: sum
		sourceColumn: leads+20

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column agendamentos
		dataType: double
		lineageTag: 24b3d2c8-61ef-4375-9de8-802a1b298612
		summarizeBy: sum
		sourceColumn: agendamentos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'conver atend x compr'
		dataType: string
		lineageTag: 1ef9c077-56ed-45dd-8245-a283fbd2db79
		summarizeBy: none
		sourceColumn: conver atend x compr

		annotation SummarizationSetBy = Automatic

	column 'referência atend x compr'
		dataType: string
		lineageTag: d6918daa-8220-4baa-ae0b-25136bbd36e8
		summarizeBy: none
		sourceColumn: referência atend x compr

		annotation SummarizationSetBy = Automatic

	column análise
		dataType: string
		lineageTag: 52baff06-0f68-4935-b0cf-3cd91081c203
		summarizeBy: none
		sourceColumn: análise

		annotation SummarizationSetBy = Automatic

	column 'conver leads x agend'
		dataType: string
		lineageTag: 9126eb81-8a0f-4a62-bc62-b1641ff98cb8
		summarizeBy: none
		sourceColumn: conver leads x agend

		annotation SummarizationSetBy = Automatic

	column 'Referência leads x agend'
		dataType: string
		lineageTag: af557782-a3a7-4131-a444-5c7ed3190709
		summarizeBy: none
		sourceColumn: Referência leads x agend

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: ea28dea2-c4dd-4294-adfb-5d0ad391aba7
		summarizeBy: none
		sourceColumn: data

		variation Variation
			isDefault
			relationship: 266dc0c1-3857-46b2-a460-ab7bd4081577
			defaultHierarchy: LocalDateTable_92a5755b-577d-4607-8750-8fbca19017a2.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition UnidadesEF-fc7d58c4-7dbc-4999-b511-cd66fbab36ec = m
		mode: import
		source =
				let
				    Fonte = Web.BrowserContents("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ48atdDXhsUk5mWb9iacd1mFxJvJC70aKuvSaVjtH7Xd-9lo_KyGz-MlaV3V14dTWGLNaL0Tx-shtg/pubhtml"),
				    #"Tabela extraída de HTML" = Html.Table(Fonte, {{"Column1", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(1)"}, {"Column2", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(2)"}, {"Column3", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(3)"}, {"Column4", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(4)"}, {"Column5", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(5)"}, {"Column6", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(6)"}, {"Column7", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(7)"}, {"Column8", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(8)"}, {"Column9", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(9)"}, {"Column10", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(10)"}, {"Column11", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(11)"}, {"Column12", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(12)"}, {"Column13", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(13)"}, {"Column14", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(14)"}, {"Column15", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(15)"}, {"Column16", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(16)"}, {"Column17", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(17)"}, {"Column18", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(18)"}, {"Column19", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(19)"}, {"Column20", "DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(21)"}}, [RowSelector="DIV[id='0'] > DIV.ritz.grid-container > TABLE.waffle > * > TR"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Tabela extraída de HTML",{{"Column1", Int64.Type}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}}),
				    #"Linhas Principais Removidas" = Table.Skip(#"Tipo Alterado",1),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Principais Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"faturamento", Currency.Type}, {"Ticket Médio", Currency.Type}, {"invest mídias", Currency.Type}, {"alcance", type number}, {"leads", type number}, {"leads+20", type number}, {"agendamentos", type number}, {"data", type date}, {"Meta", Currency.Type}, {"supermeta", Currency.Type}, {"atendidos", type number}, {"compraram", type number}})
				in
				    #"Tipo Alterado1"

	annotation PBI_ResultType = Table

