table Vendas_TOTVs
	lineageTag: 93cbe50d-4cd0-4102-b64e-625f6f7761fd

	measure 'Ofertas únicas' = DISTINCTCOUNT(Vendas_TOTVs[NR_PROPOSTA])
		formatString: 0
		lineageTag: 177a4dc8-a460-456e-b4cb-f116fb7d06b2

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Média de itens por oferta' = DIVIDE(SUM(Vendas_TOTVs[ITEM_PROPOSTA]),[Ofertas únicas])
		lineageTag: c9dd135d-e26e-4c8a-b5be-f2baac0db37e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NR_PROPOSTA
		dataType: string
		lineageTag: 4d950d0f-b99f-48a6-ba80-44dc1a9795a9
		summarizeBy: none
		sourceColumn: NR_PROPOSTA

		annotation SummarizationSetBy = Automatic

	column ITEM_PROPOSTA
		dataType: int64
		formatString: 0
		lineageTag: 069e7fd5-b99a-49fc-a702-9a0ec5614acc
		summarizeBy: sum
		sourceColumn: ITEM_PROPOSTA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column DT_UPLOAD
		dataType: dateTime
		formatString: Short Date
		lineageTag: 861eb3f2-b860-42a7-89c5-67362558fa56
		summarizeBy: none
		sourceColumn: DT_UPLOAD

		variation Variation
			isDefault
			relationship: 042e482a-723b-4ae4-99c6-e90ac5caa0b5
			defaultHierarchy: LocalDateTable_6f12660a-a366-41f3-9636-83d50f1b02bc.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DT_PRIM_VENCTO
		dataType: dateTime
		formatString: Short Date
		lineageTag: 160f836e-a6b3-48eb-896e-fa9311ff9e4e
		summarizeBy: none
		sourceColumn: DT_PRIM_VENCTO

		variation Variation
			isDefault
			relationship: c773bb27-0fc9-48a1-85a0-24a29089b764
			defaultHierarchy: LocalDateTable_11d23121-5bed-4c63-90d3-85180869a451.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HOSPEDAGEM
		dataType: string
		lineageTag: 318b548d-c2b3-4509-83aa-0c430febe723
		summarizeBy: none
		sourceColumn: HOSPEDAGEM

		annotation SummarizationSetBy = Automatic

	column CD_VENDEDOR
		dataType: string
		lineageTag: 36fa85d2-841b-47a2-8844-e81bd1c2cf19
		summarizeBy: none
		sourceColumn: CD_VENDEDOR

		annotation SummarizationSetBy = Automatic

	column CD_CLI
		dataType: string
		lineageTag: 86ffb50a-e1e6-4055-8129-22ee4980029e
		summarizeBy: none
		sourceColumn: CD_CLI

		annotation SummarizationSetBy = Automatic

	column CIDADE
		dataType: string
		lineageTag: 73f96e00-678a-4e14-bad6-46718b6193be
		summarizeBy: none
		sourceColumn: CIDADE

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: 7b715af3-dcc8-4ee6-b727-ccb552aab7f2
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	column DS_SEGMENTO
		dataType: string
		lineageTag: 41a36155-4ad0-4d95-a69e-bff415a4e143
		summarizeBy: none
		sourceColumn: DS_SEGMENTO

		annotation SummarizationSetBy = Automatic

	column DS_SUBSEGMENTO
		dataType: string
		lineageTag: 8df0263f-aacd-47a3-9b27-f9eed6f83106
		summarizeBy: none
		sourceColumn: DS_SUBSEGMENTO

		annotation SummarizationSetBy = Automatic

	column DS_CNAE
		dataType: string
		lineageTag: 3a8f6e17-5f79-46b2-80b0-b481b48c4a6f
		summarizeBy: none
		sourceColumn: DS_CNAE

		annotation SummarizationSetBy = Automatic

	column FAT_ORIGEM
		dataType: string
		lineageTag: 45b9cef7-fced-40a5-9fcf-09e04dbad079
		summarizeBy: none
		sourceColumn: FAT_ORIGEM

		annotation SummarizationSetBy = Automatic

	column FAT_FAIXA
		dataType: string
		lineageTag: 55378ed7-2f44-47d1-bfe9-a40151c5006b
		summarizeBy: none
		sourceColumn: FAT_FAIXA

		annotation SummarizationSetBy = Automatic

	column CD_PROD
		dataType: string
		lineageTag: f640a461-bf36-49e5-ac29-fda8a9fbe211
		summarizeBy: none
		sourceColumn: CD_PROD

		annotation SummarizationSetBy = Automatic

	column CD_OFERTA
		dataType: int64
		formatString: 0
		lineageTag: b0ad9bfa-5ac9-480f-b377-18687dcd91ce
		summarizeBy: sum
		sourceColumn: CD_OFERTA

		annotation SummarizationSetBy = Automatic

	column CD_MODAL_COMERC
		dataType: int64
		formatString: 0
		lineageTag: f14d66c6-f38f-43c4-ac4b-9fb93fa3a8b9
		summarizeBy: sum
		sourceColumn: CD_MODAL_COMERC

		annotation SummarizationSetBy = Automatic

	column CD_GRP_SOLUCAO
		dataType: int64
		formatString: 0
		lineageTag: 2a671031-4628-410a-839a-bbe70f555ec8
		summarizeBy: sum
		sourceColumn: CD_GRP_SOLUCAO

		annotation SummarizationSetBy = Automatic

	column CD_MARCA_TOTVS
		dataType: int64
		formatString: 0
		lineageTag: 00b53a95-b83a-4f81-9909-d47d731d1c68
		summarizeBy: sum
		sourceColumn: CD_MARCA_TOTVS

		annotation SummarizationSetBy = Automatic

	column CD_TIPO_PRODUTO
		dataType: int64
		formatString: 0
		lineageTag: f5b863d9-0fb2-4ba4-b0ed-2252fec25ffc
		summarizeBy: sum
		sourceColumn: CD_TIPO_PRODUTO

		annotation SummarizationSetBy = Automatic

	column QTD
		dataType: int64
		formatString: 0
		lineageTag: ff908ff1-9e18-40c9-84f3-3b908a60aef3
		summarizeBy: sum
		sourceColumn: QTD

		annotation SummarizationSetBy = Automatic

	column MESES_BONIF
		dataType: int64
		formatString: 0
		lineageTag: f070f448-f1ae-49ce-82cb-a47ceeec5397
		summarizeBy: sum
		sourceColumn: MESES_BONIF

		annotation SummarizationSetBy = Automatic

	column VL_PCT_DESC_TEMP
		dataType: double
		lineageTag: a4d5ed3d-4b84-4d70-ab5d-6caa78c25885
		summarizeBy: sum
		sourceColumn: VL_PCT_DESC_TEMP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VL_PCT_DESCONTO
		dataType: double
		lineageTag: 52bcf9cc-d866-4fda-bf43-a924aedc921a
		summarizeBy: sum
		sourceColumn: VL_PCT_DESCONTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRC_UNITARIO_ANONIMO
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 1545a664-da6e-4f86-9152-512325ca9608
		summarizeBy: sum
		sourceColumn: PRC_UNITARIO_ANONIMO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column VL_DESCONTO_TEMPORARIO_ANONIMO
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 93630b90-aa3a-4b47-8dd8-d8e0bc490adf
		summarizeBy: sum
		sourceColumn: VL_DESCONTO_TEMPORARIO_ANONIMO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column VL_TOTAL_ANONIMO
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: f8337c08-7f68-4911-81a4-1c78acd4d036
		summarizeBy: sum
		sourceColumn: VL_TOTAL_ANONIMO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column VL_TOTAL_TEMP_ANONIMO
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: dfaf5079-1067-406e-a4df-06482e70f14d
		summarizeBy: sum
		sourceColumn: VL_TOTAL_TEMP_ANONIMO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column VL_UNIT_TAB_ANONIMO
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 9862d79c-d2c6-40d4-8c89-8d5d15da4606
		summarizeBy: sum
		sourceColumn: VL_UNIT_TAB_ANONIMO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column VL_FULL_ANONIMO
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: de1a47a9-7dbf-43ce-8d44-566644ba7881
		summarizeBy: sum
		sourceColumn: VL_FULL_ANONIMO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column VL_DESCONTO_ANONIMO
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: e0a7dbd2-d520-427e-afcb-5ec8013a6584
		summarizeBy: sum
		sourceColumn: VL_DESCONTO_ANONIMO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 946b7676-e22a-480c-bccc-abc9f082e376
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: bb3ce455-f9cd-433b-b519-368eb09daa80
		summarizeBy: none
		sourceColumn: Nome do Mês
		sortByColumn: Mês

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 50be17f4-5714-4fa9-9091-fada676daa6f
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column Mês/Ano
		dataType: string
		lineageTag: a36e2bdd-409f-46f5-9d85-66420dd60958
		summarizeBy: none
		sourceColumn: Mês/Ano
		sortByColumn: Ano

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition Vendas_TOTVs = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\gleyd\Downloads\Conjunto_de_Dados_20230921.xlsx"), null, true),
				    #"Base de Vendas - 20230921_Sheet" = Fonte{[Item="Base de Vendas - 20230921",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Base de Vendas - 20230921_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"NR_PROPOSTA", type text}, {"ITEM_PROPOSTA", Int64.Type}, {"DT_UPLOAD", type date}, {"DT_PRIM_VENCTO", type date}, {"HOSPEDAGEM", type text}, {"CD_VENDEDOR", type text}, {"CD_CLI", type text}, {"CIDADE", type text}, {"UF", type text}, {"DS_SEGMENTO", type text}, {"DS_SUBSEGMENTO", type text}, {"DS_CNAE", type text}, {"FAT_ORIGEM", type text}, {"FAT_FAIXA", type text}, {"CD_PROD", type any}, {"CD_OFERTA", Int64.Type}, {"CD_MODAL_COMERC", Int64.Type}, {"CD_GRP_SOLUCAO", Int64.Type}, {"CD_MARCA_TOTVS", Int64.Type}, {"CD_TIPO_PRODUTO", Int64.Type}, {"QTD", Int64.Type}, {"MESES_BONIF", Int64.Type}, {"VL_PCT_DESC_TEMP", type number}, {"VL_PCT_DESCONTO", type number}, {"PRC_UNITARIO_ANONIMO", Currency.Type}, {"VL_DESCONTO_TEMPORARIO_ANONIMO", Currency.Type}, {"VL_TOTAL_ANONIMO", Currency.Type}, {"VL_TOTAL_TEMP_ANONIMO", Currency.Type}, {"VL_UNIT_TAB_ANONIMO", Currency.Type}, {"VL_FULL_ANONIMO", Currency.Type}, {"VL_DESCONTO_ANONIMO", Currency.Type}}),
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([DT_UPLOAD]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Nome do Mês", each Date.MonthName([DT_UPLOAD]), type text),
				    #"Mês Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Mês", each Date.Month([DT_UPLOAD]), Int64.Type),
				    #"Ano Inserido1" = Table.AddColumn(#"Mês Inserido", "Ano.1", each Date.Year([DT_UPLOAD]), Int64.Type),
				    #"Nome do Mês Inserido1" = Table.AddColumn(#"Ano Inserido1", "Nome do Mês.1", each Date.MonthName([DT_UPLOAD]), type text),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Nome do Mês Inserido1",{"NR_PROPOSTA", "ITEM_PROPOSTA", "DT_UPLOAD", "DT_PRIM_VENCTO", "HOSPEDAGEM", "CD_VENDEDOR", "CD_CLI", "CIDADE", "UF", "DS_SEGMENTO", "DS_SUBSEGMENTO", "DS_CNAE", "FAT_ORIGEM", "FAT_FAIXA", "CD_PROD", "CD_OFERTA", "CD_MODAL_COMERC", "CD_GRP_SOLUCAO", "CD_MARCA_TOTVS", "CD_TIPO_PRODUTO", "QTD", "MESES_BONIF", "VL_PCT_DESC_TEMP", "VL_PCT_DESCONTO", "PRC_UNITARIO_ANONIMO", "VL_DESCONTO_TEMPORARIO_ANONIMO", "VL_TOTAL_ANONIMO", "VL_TOTAL_TEMP_ANONIMO", "VL_UNIT_TAB_ANONIMO", "VL_FULL_ANONIMO", "VL_DESCONTO_ANONIMO", "Ano", "Nome do Mês", "Mês", "Nome do Mês.1", "Ano.1"}),
				    #"Colunas Mescladas" = Table.CombineColumns(Table.TransformColumnTypes(#"Colunas Reordenadas", {{"Ano.1", type text}}, "pt-BR"),{"Nome do Mês.1", "Ano.1"},Combiner.CombineTextByDelimiter("/", QuoteStyle.None),"Mês/Ano"),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Mescladas",{{"PRC_UNITARIO_ANONIMO", Currency.Type}, {"VL_DESCONTO_TEMPORARIO_ANONIMO", Currency.Type}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

