table d_Calendar
	lineageTag: c7b6f902-2593-4969-bd2d-971daca806a7

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7f2808b8-f911-46b2-8dc2-2bb0c2677ea3
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: cf9a0da4-854a-4382-bca7-616bedf07c7a
			defaultHierarchy: LocalDateTable_de5b07fb-c613-4cb8-b385-21218ff231f7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: b33b3cff-23b8-4945-a798-2130f3a7499b
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: 4702c1d4-df3e-4edf-9b3f-13f68ca999be
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 38bf7377-c1ff-4738-87dc-07289c7c646e
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column 'Semana do Mês'
		dataType: int64
		formatString: 0
		lineageTag: 0a89e2ad-36ac-478f-9bd5-0476a2eb482a
		summarizeBy: sum
		sourceColumn: Semana do Mês

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: eac7eed8-4a80-4c22-9bc2-20cdce0c0242
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: 113ccc56-ef4e-4bb3-a2dd-6de25acc9626
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	partition d_Calendar-d8f231ab-2c75-48cb-8c30-a169c2931f65 = m
		mode: import
		source =
				let
				    Fonte = Consulta1(#date(2010, 1, 1), 5000, #duration(1, 0, 0, 0)),
				    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Data"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Data", type date}}),
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Data]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
				    #"Mês Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Mês", each Date.Month([Data]), Int64.Type),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Mês Inserido",{"Data", "Ano", "Mês", "Nome do Mês"}),
				    #"Semana do Ano Inserida" = Table.AddColumn(#"Colunas Reordenadas", "Semana do Ano", each Date.WeekOfYear([Data]), Int64.Type),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Semana do Ano Inserida",{"Semana do Ano"}),
				    #"Semana do Mês Inserida" = Table.AddColumn(#"Colunas Removidas", "Semana do Mês", each Date.WeekOfMonth([Data]), Int64.Type),
				    #"Dia Inserido" = Table.AddColumn(#"Semana do Mês Inserida", "Dia", each Date.Day([Data]), Int64.Type),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Dia Inserido", "Nome do Dia", each Date.DayOfWeekName([Data]), type text),
				    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Nome do Dia Inserido",{"Data", "Mês", "Nome do Mês", "Ano", "Semana do Mês", "Dia", "Nome do Dia"})
				in
				    #"Colunas Reordenadas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

